### ISSUE TITLE
Cannot find module 'cdk' or its corresponding type

### ISSUE THREAD

**Issue by MilanObrenovic** [hackingharold/ngx-dropzone#21]
![image](https://github.com/hackingharold/ngx-dropzone/assets/56999235/78b0cd23-0c80-40f8-b67a-66b2f867f1b3)

This error pops up when i add

```typescript
import { DropzoneMaterialModule } from "@ngx-dropzone/material";
```

but adding

```typescript
import { DropzoneCdkModule } from "@ngx-dropzone/cdk";
```

there is no error. i'm using angular 16.0.2

**Comment by hackingharold** [comment]
Hi @MilanObrenovic,

in order to use the Material implementation, you also have to install the CDK.
So your `AppModule` should import both the `DropzoneCdkModule` and the `DropzoneMaterialModule` to work.

Hope this helps.
