### ISSUE TITLE
Update to Angular 17

### ISSUE THREAD

**Issue by stefanbildl** [hackingharold/ngx-dropzone#65]
# Support Angular 17

Angular 17 is out. 
I updated it for you - see my pull request.

Thank you for this great library!

**Comment by stefanbildl** [comment]
See also my pull request:
https://github.com/hackingharold/ngx-dropzone/pull/66

**Comment by hackingharold** [comment]
Hi there,

thanks for your contribution. I released an updated version with some additional features.
Take a look at the [releases section](https://github.com/hackingharold/ngx-dropzone/releases).
