### ISSUE TITLE
Suggestion: support a directory selection in Open File dialog

### ISSUE THREAD

**Issue by alexandis** [hackingharold/ngx-dropzone#74]
Harold,

is it possible to make a directory selection working not only via drag-n-drop, but also by directly selecting it in Open File dialog? From what I heard, it should work in the majority of browsers, including Chrome...

Also - just in case the information might be in handy - I've actually overridden the handling of the selection to [include the information about the relative path of each of the selected files](https://github.com/hackingharold/ngx-dropzone/issues/60#issuecomment-1907290810).

**Comment by hackingharold** [comment]
Hi @alexandis,

to allow directory selection in the open file dialog, just add the [`webkitdirectory`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file#webkitdirectory) attribute to your `<input type="file" />` element. Hope this helps.

**Comment by alexandis** [comment]
When I use this attribute - there is a system message, offering me to upload files somewhere (when I agree - nothing happens). It is not an expected behavior for me, saying honestly. What I would like to have instead - selecting folder acted in the same way as if I just "drag-n-drop"-ed this folder, so `drop` event would raised eventually...

**Comment by alexandis** [comment]
I've tried `webkitdirectory` again with `ngModelChange` - at least it process ALL the files, even if there are thousands of them. But - this standard dialog does not allow me selecting several folders... :( so it is not so flexible as drag-n-drop, unfortunately.
Anyway, I think I can close the original bug, because - with specific limitations - the directory selection DOES work.
