### ISSUE TITLE
Suggestion: allow null or empty values when using ‎FileInputValidators

### ISSUE THREAD

**Issue by mcms9090** [hackingharold/ngx-dropzone#75]
Hi there!

Thanks for this useful library. Would it be possible to allow for the FileInputValidators validator to have null or empty values? There are cases where I want to limit the types of files to be submitted in a form but the field itself could be optional, but the validator returns false if there is no file so it gets marked as invalid.

**Comment by hackingharold** [comment]
Hi @mcms9090,

I am not sure if I got your problem correctly. To set the allowed file types you're supposed to use the `accept` attribute.

```html
<input type="file" fileInput accept="image/png" />
```

This should not interfere with any optional form values. If this does not solve your problem, please provide a code example.

Happy coding!

**Comment by mcms9090** [comment]
Thanks for your reply. I was using FileInputValidators.accept('image/*,application/pdf') in a reactive form, but the control always comes as invalid when there is no value, and I was trying to limit the allowed types but not make the field required

`    this.form = this.formBuilder.group({
      optionalPdfOrImage: [null, FileInputValidators.accept('image/*,application/pdf')],
    });`

**Comment by hackingharold** [comment]
I see, then this is indeed a bug in the library. I will prepare a fix.

**Comment by hackingharold** [comment]
Please try again using v17.3.0.

**Comment by mcms9090** [comment]
Works great. Thanks!
