### ISSUE TITLE
no translation on iOS context menu

### ISSUE THREAD

**Issue by Hyphaed** [hackingharold/ngx-dropzone#77]
when selecting files or image to upload it shows always english language 

"Photo Library"
"Choose Files"

even when iOS system is set to spanish language or any other language

![Screenshot from 2024-05-14 18-57-16](https://github.com/hackingharold/ngx-dropzone/assets/19622367/8af87969-7b05-41c4-8c50-fccca5e11406)

**Comment by hackingharold** [comment]
Well, hello at first. 👋

These button labels are part of the native OS behavior and are out of scope of this library. We do not set them manually anywhere in our code. You might want to play around with your Browser's language or the `<html lang="es">` tag.

**Comment by Hyphaed** [comment]
thanks
