### ISSUE TITLE
Cannot distinguish between event handlers when doing drag-n-drop

### ISSUE THREAD

**Issue by alexandis** [hackingharold/ngx-dropzone#79]
Hi,
I am back :)
I've used the following markup to cover both drag-n-drop and usual selection for multiple file upload:

```
<ngx-mat-dropzone (drop)="onDropDocuments($event)">
    <input type="file" fileInput [ngModel]="files" [ngModelOptions]="{ standalone: true }" [multiple]="true"(ngModelChange)="onSelectDocuments($event)" />
</ngx-mat-dropzone>
```

Unfortunately, it works well only for an ordinary select, because only `onSelectDocuments` is triggered. When I use drag-n-drop, both `onSelectDocuments` and `onDropDocuments` handlers are triggered and as a result, I get the issue, because the code has to process the same logic twice. How to avoid this and clearly divide the handlers?

I used some custom logic, that's why I use `onDropDocuments` handler. And also I found using ngModel in my case instead of formControl to be preferrable.

In fact, the main reason for having the custom code was to get the initial source path of the file by all means, since we needed to pass this info to server. If I could obtain this information in other way, probably I would get rid of the issue as well by eliminating some custom handlers...

**Comment by alexandis** [comment]
Hi.

I use my custom logic in `onDropDocuments` method to handle a drag-n-drop scenario. This logic creates the collection of files to-be-uploaded, filling the original file path using `FileSystemEntry` => `fullPath` property (otherwise the original file name does not contain this information). Here, I have to copy the original file to a new file to change its name, because `File` is immutable (`this.files.push(this.copyFile(file, fileEntry.fullPath.replace(/^\/[A-Z]_drive/, '')));`)

And I use `onSelectDocuments` to handle an ordinary logic - selecting files folder with standard system "Open" button - in this case the original file path is available straight in `File` => `name`. In general, I use `onSelectDocuments` to build a common logic of displaying the files to-be-uploaded (the folder structure with the total amount of files and its volume per each subfolder), no matter if it's a drag-n-drop or a system select.

And I am getting issues related to the fact that for drag-n-drop both methods are called. So I would appreciate your proposals how to simplify my logic to still achieve the goal.

The team member broke the page availability and I cannot test my page right away. Are you implying that I can use `webkitRelativePath` next to `webkitdirectory` and it will resolve my issue and besides I will be able to through away some of my code?

**Comment by hackingharold** [comment]
Please have a look at PR #80. This might fix your problem.

I first decided to ignore the relative path info, but I thinks it's time to add it back in.
The only way to achieve a consistent behavior is to add a new property.

Please review the PR code. You might want to checkout the branch and try it locally.
If this fits your needs, we may release a new version.

**Comment by alexandis** [comment]
Thank you. Sorry, don't know what is the correct way to check your changes. I've installed GitHub Desktop, still cannot see how to use your PR code...

**Comment by hackingharold** [comment]
After cloning the repo and `npm install` follow [these steps](https://github.com/hackingharold/ngx-dropzone?tab=readme-ov-file#development-server) to run a test app.
Then upload some files and check if the `relativePath` property is set. You should be able to keep the file paths on drop AND when using the file picker. 
Migrating to Angular 18 is recommended anyway, as a workaround you could install the latest version with `--force` flag in your project. 

About your other question, the internal state is stored in the `value` property.
I would recommend to use a `FormControl` for the most flexible state management.
Use the property `mode` (see [config](https://github.com/hackingharold/ngx-dropzone?tab=readme-ov-file#development-server)) to change the behavior. By default, a second file selection will overwrite the first one. But you may also "stack" all selected files.

**Comment by alexandis** [comment]
Hi Paul.
Thank you, I've installed PR version to my project.
Seems like it does not work fully correct or I am missing something.
Here is my usage (for "folder selection" scenario):
```
                <ngx-mat-dropzone>
                  <input type="file" fileInput [(ngModel)]="files" [ngModelOptions]="{ standalone: true }" [multiple]="true" relativePath mode="append" webkitdirectory (ngModelChange)="accumulateFilesAndRecalculateFolders($event)" />
                </ngx-mat-dropzone>
```
When I select the folder in a system way, via button click - everything looks as expected.
However, when I drag-n-drop - `webkitRelativePath` property is still zero (and file `name` contains only name, no path info either).
Another issue: I have the button to remove the selected files, which does this:
`this.files = [];`
However, when I select the files again, it pulls the previously selected files from somewhere...

**Comment by hackingharold** [comment]
Hey, thanks for the feedback.
You're almost there. On drop, the `webkitRelativePath` property will be empty, since I can't overwrite it with the full path value because it's readonly. Therefore, I added the new `relativePath` property which should have the expected value.

As for your other bug of clearing the array, I will have to look into this in the next few days. Maybe use a `FormControl` as a workaround?

When using `mode="replace"` (which is the default) on the `<input type="file">` element, no duplicates should be possible because the files array will be reset on each change. Any other validation will be left to you as the consumer. You might check for duplicate file names in the `FormControl` `valueChanges` handler.

**Comment by alexandis** [comment]
Maybe I am missing something obvious, but on drag-n-drop `console.log((file as any).relativePath)` returns me `undefined`...

> Maybe use a FormControl as a workaround
I might check it out later on, but if it was possible to make it work for `ngModel`, I would be happy ;)

**Comment by hackingharold** [comment]
Okay, so let's try to figure this out.
Please setup the local playground dev app as described in my previous post. With this minimum example I got it working as expected.

```ts
import { Component } from '@angular/core';
import { File } from '@ngx-dropzone/cdk';

@Component({
  selector: 'app-root',
  template: `<div class="app-container">
    <mat-form-field appearance="fill">
      <mat-label>Drop anything!</mat-label>
      <ngx-mat-dropzone>
        <input
          type="file"
          fileInput
          multiple
          webkitdirectory
          [(ngModel)]="files"
          [ngModelOptions]="{ standalone: true }"
          (ngModelChange)="buildFolderOutput()"
        />
      </ngx-mat-dropzone>
    </mat-form-field>
  </div>`,
})
export class AppComponent {
  files: File[] = [];

  buildFolderOutput() {
    this.files.forEach((f) => console.log(f.relativePath));
  }
}
```

**Comment by hackingharold** [comment]
To be able to reset the internal value, even with `mode="append"`, I expanded the PR to add a new `clear()` method to the directive. Use it like so.

```html
<input type="file" fileInput #fi="fileInput" mode="append" />

<button (click)="fi.clear()">Reset</button>
```

**Comment by alexandis** [comment]
Thank you, i will try this on Monday. Quick question: is it possible to delete a single item from files array? I should have asked that from the start, not deleting all elements, sorry.

**Comment by hackingharold** [comment]
Yes, if you have set `mode="replace"` you can just update your files array.

```ts
this.files = this.files.filter(f => f.name !== "test");
```

**Comment by alexandis** [comment]
> Yes, if you have set `mode="replace"` you can just update your files array.
> 
> ```ts
> this.files = this.files.filter(f => f.name !== "test");
> ```

Well, I prefer `this.files.splice(index, 1)` - I think it might be faster... But anyway, the deletion is OK.
So underlining, the latest version works. Small note: to remove all the elements, I really need to use `clear` method, otherwise (if I do `this.files = []`) it still retains the old value which seems a bit weird to me.

All other things work, thank you very much!

**Comment by alexandis** [comment]
Hi. I've compiled the latest version and still observe the bug.
Step to reproduce:
1) Drag file 1; Result: file 1 appears in UI;
2) Drag file 2: Result: file 2 appears in UI, but also file 1 appears in UI again - duplicate.

**Comment by alexandis** [comment]
Looks fine now. Could you please publish the version?

**Comment by hackingharold** [comment]
I want to interfere with the default Browser behavior as less as possible. Therefore, I will leave the handling of this edge case to the consumer (n this case you), depending on the use case.

I will now merge the PR and release a new version that you might want to pull into your project.

**Comment by alexandis** [comment]
Hi, @hackingharold.
I occasionally found out, that `relativePath` does not work anymore as it worked before - at least, on the latest version of Chrome.
Here is the source file:
![image](https://github.com/user-attachments/assets/c77133e7-ab35-4597-9dee-4f8944cf58f0)
Please have a look - this is what is looks like when I drag-n-drop a file:
![image](https://github.com/user-attachments/assets/48e64e03-59fb-472b-be79-bc77852ea5a5)
And here is what it looks like when I use a standard "open" way:
![image](https://github.com/user-attachments/assets/4f94b579-e913-4a61-9634-56e4dcb01f33).
If I use `webkitdirectory` attribute on other page, where I need to select a whole folder - it does not look right either, you can check it out yourself...

**Comment by hackingharold** [comment]
Hey,

I just tested this with `ngx-dropzone@18.1.0` in Chrome 126 using my StackBlitz example and it's still working as expected.
Note that the `webkitdirectory` attribute is required to be able to get the relative path when using the native file picker.

Please provide some more information if you cannot get it to work.

**Comment by hackingharold** [comment]
I am confused now, your example is working as expected for me. 
Please see the following table and explain what you expect differently:

|                                    | `webkitdirectory` ❌                                              | `webkitdirectory` ✅                                              |
|------------------------------------|----------------------------------------------------------------|----------------------------------------------------------------|
| selecting file(s) from file picker | `relativePath` is empty because no directory was selected        | not possible, forbidden by Browser                             |
| selecting folder from file picker  | not possible, forbidden by Browser                             | `relativePath` is set based on selected folder                   |
| dropping file(s)                   | `relativePath` equals the name because no directory was selected | `relativePath` equals the name because no directory was selected |
| dropping folder                    | `relativePath` is set based on dropped folder                    | `relativePath` is set based on dropped folder                    |

For the file picker, you have to decide to either allow folders or single files by setting the `webkitdirectory` attribute. This is native Browser behavior I cannot do anything about.

**Comment by alexandis** [comment]
Thank you, I understand now... A _directory selection mode_ works well, you are right - my bad (indeed - it's RELATIVE path, not ABSOLUTE :)).

Regarding a _file selection mode_, which now I am coping with... So, to your knowledge, there's no any way to find out an absolute source path of the file to be uploaded via javascript?

**Comment by alexandis** [comment]
Thank you so much.

**Comment by alexandis** [comment]
One more question: how to differentiate between the previously added files and a new chunk - the files which are being added now? I've tried to use `formControl` for that:

`this.files.valueChanges.subscribe((files) => ...) // this.files is formControl as in your example`

expecting that "files" parameter would contain only the current chunk, but it contains WHOLE collection...

I need the differentiation, because I add some custom form controls accompanying the files to be uploaded.
