### ISSUE TITLE
Is there a way to make the drag-n-drop area the size of the form?

### ISSUE THREAD

**Issue by SmearyQuill** [hackingharold/ngx-dropzone#81]
Hi and thanks for taking time to review my questions.

I'm viewig the DEMO available from the readme and i'm applying the next css 

`    mat-form-field {
      width: 100%;
      height: 100%
    }`

this makes the mat-form-field component look like this:
![image](https://github.com/hackingharold/ngx-dropzone/assets/35876982/23a9d28f-a5f3-4578-95e1-9e6078a01022)

the problem is that the drag-n-drop area is only available in the next portion of the whole mat-form-field
![image](https://github.com/hackingharold/ngx-dropzone/assets/35876982/ed32540e-00d1-48dd-ba18-c563183e6281)

Is there a way to avoid this and make the drag-n-drop area as big as the mat-form-field? 

Thanks in advance.

**Comment by hackingharold** [comment]
Hi @SmearyQuill,

thanks for trying out the demo. To change the height of the dropzone, you would have to pierce into the form-field contents.

```css
::ng-deep {
    ngx-mat-dropzone,
    .mat-mdc-form-field-flex,
    .mat-mdc-form-field-infix {
        height: 100%;
    }
}
```

Please note that this might lead to some visual inconsistencies, as the `mat-form-field` is not intended to be used that way. The `ngx-dropzone` library also provided a headless (unstyled) CDK, so you might be better off to completely style it yourself (see [here](https://github.com/hackingharold/ngx-dropzone?tab=readme-ov-file#extensibility)).
