### ISSUE TITLE
Feature: validate maxSize of all files

### ISSUE THREAD

**Issue by BeniFreitag** [hackingharold/ngx-dropzone#88]
Please add a validator for the max file size of all files. This sample would work:

```typescript
/**
 * Checks if the file size of all files is equal or smaller than the allowed size.
 * Validates every file within array. Returns no error when null.
 */
static maxSizeAllFiles(max: number): ValidatorFn {
  return (control: AbstractControl<File[]>): ValidationErrors | null => {
    const totalFileSize = control.value.reduce((partialSum, a) => partialSum + a.size, 0)
    const valid = totalFileSize <= max
    return valid ? null : { maxSizeAllFiles: { value: control.value, max } }
  }
}
````

**Comment by hackingharold** [comment]
Hey there,

thanks for your contribution.

You are free to add any custom validators to your implementation as described in the readme. 
For now, I want to keep the library as small as possible and in my opinion this is not something we need in the lib necessarily. 

I will leave the issue open and see if the issue gets some upvotes.
