### ISSUE TITLE
FileInputValidator accept is not case insensitive

### ISSUE THREAD

**Issue by nischi** [hackingharold/ngx-dropzone#97]
Hi @hackingharold 

I realized that the accept Validator is not working like the accept attribute in HTML. The accept attribute is case insensitive but the accept Validator in `FileInputValidator` is case sensitive. 

The `parseAttribute` function get the accept attribute value as lowercase and the check in `isAcceptedByExtension` works with `endsWith` which is case sensitive. So all files which has upper case file extension will be a wrong extension. 

I will provide a pull request in the near future.

kind regards,
nischi

**Comment by hackingharold** [comment]
Hi @nischi,

very well spotted, thanks for your contribution.

**Comment by nischi** [comment]
Thanks a lot
